package helpsessions;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Time;
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

public class TimePanel extends javax.swing.JPanel {

    public TimePanel(final Time[] t, final MainPanel mp, final String day) {
        setLayout(new GridBagLayout());
        setBackground(Color.WHITE);
        GridBagConstraints gbc = new GridBagConstraints();
        ButtonGroup jbg = new ButtonGroup();

        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm a");
        Font font = new Font("Calibri Light", Font.PLAIN, 13);

        JRadioButton timeBtn = new JRadioButton();
        timeBtn.setFont(font);
        timeBtn.setText(sdf.format(t[0]) + " - " + sdf.format(t[1]));
        timeBtn.setBackground(Color.WHITE);
        mp.timesBG.add(timeBtn);
        gbc.gridx = 0;
        gbc.gridy = gbc.RELATIVE;
        add(timeBtn, gbc);

        timeBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mp.dayToPass = day;
                mp.showFinalize(t);

            }
        });


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
